create table
  public.usernames (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    username text not null,
    user_id uuid null,
    name text not null default ''::text,
    image_path text null,
    constraint usernames_pkey primary key (id),
    constraint usernames_username_key unique (username),
    constraint usernames_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;